version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - 26016:27017
    volumes:
      - bottom-trade-mongo-data:/data/db
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  bottom-trade-mongo-data:
networks:
  database:
