defaults:
  switch_days: &switch_days
    - 20
    - 45
  # 普通品种主力合约列表
  main_symbols_c: &main_symbols_c
    - 1
    - 5
    - 9
  # 螺纹主力合约列表
  main_symbols_rb: &main_symbols_rb
    - 1
    - 5
    - 10
  # 有色金属主力合约列表
  main_symbols_nfm: &main_symbols_nfm
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  # 贵金属主力合约列表
  main_symbols_pm: &main_symbols_pm
    - 2
    - 6
    - 8
    - 10
    - 12
  long: &long
    base_scale: 0.03
    stop_loss_scale: 1
    profit_start_scale_1: 3
    promote_scale_1: 6
    promote_target_1: 3
    profit_start_scale_2: 1.5
    promote_scale_2: 3
    promote_target_2: 1
  short: &short
    base_scale: 0.03
    stop_loss_scale: 1
    profit_start_scale: 8
    promote_scale: 3
    promote_target: 1
open_pos_scale: 0.2
futures:
# 大连商品交易所
  # - symbol: KQ.m@DCE.a
  #   name: 豆一
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.c
  #   name: 玉米
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.cs
  #   name: 淀粉
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.eb
  #   name: 苯乙烯
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.eg
  #   name: 乙二醇
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.i
  #   name: 铁矿
  #   is_active: 1
  #   multiple: 100
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.j
  #   name: 焦炭
  #   is_active: 1
  #   multiple: 100
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.jd
  #   name: 鸡蛋
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.jm
  #   name: 焦煤
  #   is_active: 1
  #   multiple: 60
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.l
  #   name: 塑料
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.m
  #   name: 豆粕
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.p
  #   name: 棕榈
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.pg
  #   name: 液化石油气
  #   is_active: 1
  #   multiple: 20
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.pp
  #   name: PP
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.rr
  #   name: 粳米
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.v
  #   name: PVC
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.y
  #   name: 豆油
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@DCE.lh
  #   name: 生猪
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
# 郑州商品交易所
  # - symbol: KQ.m@CZCE.AP
  #   name: 苹果
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_rb
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.CF
  #   name: 棉花
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.FG
  #   name: 玻璃
  #   is_active: 1
  #   multiple: 20
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.MA
  #   name: 甲醇
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.OI
  #   name: 菜油
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.PF
  #   name: 短纤
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.RM
  #   name: 菜粕
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.SA
  #   name: 纯碱
  #   is_active: 1
  #   multiple: 20
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.SM
  #   name: 锰硅
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.SR
  #   name: 白糖
  #   is_active: 1
  #   multiple: 10
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.TA
  #   name: PTA
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.TA
  #   name: PTA
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CZCE.SF
  #   name: 硅铁
  #   is_active: 1
  #   multiple: 5
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_c
  #   long: *long
  #   short: *short
  - symbol: KQ.m@CZCE.UR
    name: 尿素
    is_active: 1
    multiple: 20
    switch_days: *switch_days
    main_symbols: *main_symbols_c
    long: *long
    short: *short
# 上海期货交易所
#   - symbol: KQ.m@SHFE.cu
#     name: 沪铜
#     is_active: 1
#     multiple: 5
#     switch_days: *switch_days
#     main_symbols: *main_symbols_nfm
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.au
#     name: 沪金
#     is_active: 1
#     multiple: 1000
#     switch_days: *switch_days
#     main_symbols: *main_symbols_pm
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.ag
#     name: 沪银
#     is_active: 1
#     multiple: 15
#     switch_days: *switch_days
#     main_symbols: *main_symbols_pm
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.zn
#     name: 沪锌
#     is_active: 1
#     multiple: 5
#     switch_days: *switch_days
#     main_symbols: *main_symbols_nfm
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.al
#     name: 沪铝
#     is_active: 1
#     multiple: 5
#     switch_days: *switch_days
#     main_symbols: *main_symbols_nfm
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.ru
#     name: 橡胶
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.rb
#     name: 螺纹
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_rb
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.fu
#     name: 燃油
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.hc
#     name: 热卷
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.bu
#     name: 沥青
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.pb
#     name: 沪铅
#     is_active: 1
#     multiple: 5
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.ni
#     name: 沪镍
#     is_active: 1
#     multiple: 1
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.sn
#     name: 沪锡
#     is_active: 1
#     multiple: 1
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.sp
#     name: 纸浆
#     is_active: 1
#     multiple: 10
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
#   - symbol: KQ.m@SHFE.ss
#     name: 不锈钢
#     is_active: 1
#     multiple: 5
#     switch_days: *switch_days
#     main_symbols: *main_symbols_c
#     long: *long
#     short: *short
# # 上海国际能源交易中心
#   - symbol: KQ.m@INE.sc
#     name: 原油
#     is_active: 1
#     multiple: 1000
#     switch_days: *switch_days
#     main_symbols: *main_symbols_nfm
#     long: *long
#     short: *short
# 中国金融期货交易所
  # - symbol: KQ.m@CFFEX.TF
  #   name: 5年期国债期货
  #   is_active: 1
  #   multiple: 10000
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CFFEX.TS
  #   name: 2年期国债期货
  #   is_active: 1
  #   multiple: 20000
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CFFEX.T
  #   name: 10年期国债期货
  #   is_active: 1
  #   multiple: 10000
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CFFEX.IH
  #   name: 上证50指数期货
  #   is_active: 1
  #   multiple: 300
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CFFEX.IC
  #   name: 中证500指数期货
  #   is_active: 1
  #   multiple: 200
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
  # - symbol: KQ.m@CFFEX.IF
  #   name: 沪深300指数期货
  #   is_active: 1
  #   multiple: 300
  #   switch_days: *switch_days
  #   main_symbols: *main_symbols_nfm
  #   long: *long
  #   short: *short
