defaults:
  switch_days: &switch_days
    - 20
    - 45
  # 普通品种主力合约列表
  main_symbols_c: &main_symbols_c
    - 1
    - 5
    - 9
  # 螺纹主力合约列表
  main_symbols_rb: &main_symbols_rb
    - 1
    - 5
    - 10
  # 有色金属主力合约列表
  main_symbols_nfm: &main_symbols_nfm
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  # 贵金属主力合约列表
  main_symbols_pm: &main_symbols_pm
    - 2
    - 6
    - 8
    - 10
    - 12
  # 奇数月主力合约列表
  main_symbols_odd: &main_symbols_odd
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
  long: &long
    base_scale: 0.03
    stop_loss_scale: 1
    profit_start_scale_1: 3
    promote_scale_1: 6
    promote_target_1: 3
    profit_start_scale_2: 1.5
    promote_scale_2: 3
    promote_target_2: 1
  short: &short
    base_scale: 0.03
    stop_loss_scale: 1
    profit_start_scale: 8
    promote_scale: 3
    promote_target: 1
open_pos_scale: 0.2
futures:
  - symbol: KQ.m@SHFE.hc
    name: 热卷
    is_active: 1
    multiple: 10
    switch_days: *switch_days
    main_symbols: *main_symbols_rb
    long: *long
    short: *short
 